# Generated by Django 2.1.1 on 2019-04-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190405_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sections',
            field=models.ManyToManyField(related_name='article', through='articles.ArticleSection', to='articles.Section'),
        ),
    ]
