# Generated by Django 2.1.1 on 2019-04-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190405_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sections',
            field=models.ManyToManyField(through='articles.ArticleSection', to='articles.Section'),
        ),
    ]
